name = "ExprGraphExplorer"
uuid = "c9fc7d07-15e8-4fd8-b152-23c2424d2de2"
version = "0.1.0"
authors = ["Benoît Legat <benoit.legat@gmail.com>"]

[deps]
Latexify = "23fbe1c1-3f47-55db-b15f-69d7ec21a316"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
Latexify = "0.16.12"
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
